### ISSUE TITLE
Incorrect input parameter "sensitive_system"

### ISSUE THREAD

**Issue by vjeffPeters** [mitre/microsoft-windows-10-stig-baseline#13]
The actual parameter name is "is_sensitive_system".  Readme.md is listing all references to this parameter as "sensitive_system" including the example.

**Comment by aaronlippold** [comment]
I think that is a bug, I will ask the author which one they wanted to standardize on.

**Comment by karikarshivani** [comment]
My vote is to standardize on "sensitive_system"
@burnsjared0415 ?

**Comment by aaronlippold** [comment]
I agree, let's standardize on this

**Comment by karikarshivani** [comment]
The only instances I found with `is_sensitive_system` were:

- [V-63579](https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/master/controls/V-63579.rb#L122)
- [V-63583](https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/master/controls/V-63583.rb#L102)
- [V-63587](https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/master/controls/V-63587.rb#L118)

PR #16 includes the updated input names.
