### ISSUE TITLE
update to just call input directly

### ISSUE THREAD

**Issue by aaronlippold** [mitre/microsoft-windows-10-stig-baseline#15]
https://github.com/mitre/microsoft-windows-10-stig-baseline/blob/0f95e4658095effb80f475b9b76f35866cbbfeee/controls/V-63405.rb#L48

**Comment by Amndeep7** [comment]
@aaronlippold this behavior still seems to be bugged on inspec's side and they appear to be reluctant to fix it.  closing for now.  please reopen if necessary.
