### ISSUE TITLE
Typo in V-63829

### ISSUE THREAD

**Issue by scotdewerth** [mitre/microsoft-windows-10-stig-baseline#24]
The registry key to check for "Run all Administrators in Admin approval mode" is Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA

The faulty code for the test looks for 'EnableLUAs' causing the control to fail audit even if properly configured. This test was run on Windows 10 Professional version 21H1 (OS build 19043.1165)

The following code fixed this issue for this build

describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System') do
    it { should have_property 'EnableLUA' }
    its('EnableLUA') { should cmp 1 }
  end

**Comment by aaronlippold** [comment]
A PR would be great. Would you be able to submit one?

Thanks,
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by scotdewerth** [comment]
Unsure.  Per the creating a Pull request, I need to have write access to your repository or I have to fork it to mine. Do you want me to fork it to mine? Not Git user except for pulls in most cases.  My git desktop only gives me the option to write the changes to my forked repository.

"Note: To open a pull request in a public repository, you must have write access to the head or the source branch or, for organization-owned repositories, you must be a member of the organization that owns the repository to open a pull request."

**Comment by aaronlippold** [comment]
Usually people just fork it create the branch and then create a pull
request on the master
