### ISSUE TITLE
V-63373 - issue with permission and how to get the right info

### ISSUE THREAD

**Issue by burnsjared0415** [mitre/microsoft-windows-10-stig-baseline#7]
After doing some research i have found that the command we are using to pull the permissions does not take into account the way Microsoft handles permissions on two of the accounts that are checked. When you run (get-acl <folder name>).access | ft IdentityReference,FileSystemRights,AccessControlType,IsInherited,InheritanceFlags -auto, you will get a table that shows you the permission for Builtin\Administrator and NT Authority\SYSTEM pull 268435456 which is full-control over the folder, but the control is looking for full-control as a string. Need to work through how to solve this.

**Comment by aaronlippold** [comment]
Resolved in 1.19.0
